# Generated by Django 3.2.6 on 2021-09-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='linprog_vars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var', models.FloatField()),
            ],
        ),
    ]
