# Generated by Django 3.2.6 on 2021-09-11 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torp', '0002_linprog_vars'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inventory_Data',
            new_name='InventoryData',
        ),
        migrations.DeleteModel(
            name='linprog_vars',
        ),
    ]
